---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-keys
type: Opaque
data:
  apiserver-key.pem: {{ .Values.tls.key | b64enc }}
  etcd-client-key.pem: {{ .Values.apiserver.etcd.tls.key | b64enc }}
