---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
  annotations:
{{- if .Values.monitoring.prometheus.enabled }}
{{ tuple .Values.monitoring.prometheus.coredns | include "helm-toolkit.snippets.prometheus_service_annotations" | indent 4 -}}
{{- end }}
spec:
  selector:
    {{ .Values.service.name }}: enabled
  clusterIP: {{ .Values.service.ip }}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
