{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $envAll.Values.service.name }}
data:
  client-ca.pem: {{ $envAll.Values.tls.client.ca | quote }}
  peer-ca.pem: {{ $envAll.Values.tls.peer.ca | quote }}
  manager-etcd-client.pem: {{ $envAll.Values.manager.tls.cert | quote }}
{{- range .Values.nodes }}
  {{- $node := . }}
  {{ $node.name }}-etcd-client.pem: {{ $node.tls.client.cert | quote }}
  {{ $node.name }}-etcd-peer.pem: {{ $node.tls.peer.cert | quote }}
{{- end }}
