---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.service.name }}-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.service.name }}-manager
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.name }}-manager
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
