{{- $envAll := . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $envAll.Values.service.name }}
type: Opaque
data:
{{- range .Values.nodes }}
  {{- $node := . }}
  {{ $node.name }}-etcd-client-key.pem: {{ $node.tls.client.key | b64enc }}
  {{ $node.name }}-etcd-peer-key.pem: {{ $node.tls.peer.key | b64enc }}
{{- end }}
