{{- $envAll := . }}
{{- range .Values.nodes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $envAll.Values.service.name }}-{{ .name }}
type: Opaque
data:
  client-ca.pem: {{ .tls.client.ca | b64enc }}
  etcd-client.pem: {{ .tls.client.cert | b64enc }}
  etcd-client-key.pem: {{ .tls.client.key | b64enc }}
  peer-ca.pem: {{ .tls.peer.ca | b64enc }}
  etcd-peer.pem: {{ .tls.peer.cert | b64enc }}
  etcd-peer-key.pem: {{ .tls.peer.key | b64enc }}
{{- end }}
