---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-discovery
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    {{ .Values.service.name | quote }}: server
  clusterIP: None
  ports:
    - name: etcd-client-ssl
      port: {{ .Values.service.ports.client }}
      targetPort: {{ .Values.service.target_ports.client }}
    - name: etcd-server-ssl
      port: {{ .Values.service.ports.peer }}
      targetPort: {{ .Values.service.target_ports.peer }}
