---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-etcd
spec:
  template:
    metadata:
      labels:
        tier: control-plane
        component: kube-etcd
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: etcd
          image: {{ .Values.etcd.image }}
          imagePullPolicy: {{ .Values.etcd.image_pull_policy }}
          env:
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://$(ETCD_NAME):2379
            - name: ETCD_DATA_DIR
              value: /var/lib/etcd
            - name: ETCD_DISCOVERY_SRV
              value: etcd-discovery
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: existing
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: promenade-kube-etcd-token
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:2380
          ports:
            - name: client
              containerPort: 2379
            - name: peer
              containerPort: 2380
          volumeMounts:
            - name: data
              mountPath: /var/lib/etcd
      volumes:
        - name: data
          hostPath:
            path: /var/lib/etcd
