---
apiVersion: v1
kind: Service
metadata:
  name: etcd-discovery
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-etcd
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  selector:
    tier: control-plane
    component: kube-etcd
  ports:
    - name: etcd-client
      port: 2379
    - name: etcd-server
      port: 2380
