---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    tier: control-plane
    component: kube-etcd
spec:
  selector:
    tier: control-plane
    component: kube-etcd
  ports:
    - name: etcd-client
      port: 2379
