---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-bin
data:
  anchor: |+
{{ tuple "bin/_anchor.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  pre_stop: |+
{{ tuple "bin/_pre_stop.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
