---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-scheduler-etc
data:
  cluster-ca.pem: {{ .Values.secrets.tls.ca | quote }}
  kubeconfig.yaml: |+
{{ tuple "etc/_kubeconfig.yaml.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  kubernetes-scheduler.yaml: |+
{{ tuple "etc/_kubernetes-scheduler.yaml.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  scheduler.pem: {{ .Values.secrets.tls.cert | quote }}
