---
apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: {{ .Values.service.name }}-anchor
  labels:
    application: kubernetes
    component: kubernetes-scheduler-anchor
spec:
  selector:
    matchLabels:
      {{ .Values.service.name | quote }}: anchor
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
      labels:
        {{ .Values.service.name | quote }}: anchor
    spec:
      hostNetwork: true
      dnsPolicy: {{ .Values.anchor.dns_policy }}
      nodeSelector:
        {{ .Values.anchor.node_selector.key }}: {{ .Values.anchor.node_selector.value }}
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: anchor
          image: {{ .Values.images.anchor }}
          command:
            - /tmp/bin/anchor
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/bin/pre_stop
          volumeMounts:
            - name: bin
              mountPath: /tmp/bin
            - name: etc
              mountPath: /configmap
            - name: host
              mountPath: /host
            - name: secret
              mountPath: /secret
      terminationGracePeriodSeconds: {{ .Values.anchor.termination_grace_period }}
      volumes:
        - name: bin
          configMap:
            name: {{ .Values.service.name }}-bin
            defaultMode: 0555
        - name: etc
          configMap:
            name: {{ .Values.service.name }}-etc
            defaultMode: 0444
        - name: host
          hostPath:
            path: /
        - name: secret
          secret:
            secretName: {{ .Values.service.name }}
            defaultMode: 0444
