---
- name: Ensures /etc/kubernetes dir exists
  when:
    bootstrap_enabled
  file:
    path: /etc/kubernetes
    state: directory

- name: copy kubeconfig credentials
  when:
    bootstrap_enabled
  command: cp /tmp/bootkube/assets/auth/kubeconfig /etc/kubernetes/kubeconfig
  args:
    creates: /etc/kubernetes/kubeconfig

- name: copy kubernetes manifests
  when:
    bootstrap_enabled
  command: cp -a /tmp/bootkube/assets/manifests /etc/kubernetes/
  args:
    creates: /etc/kubernetes/manifests

- name: fetch kubeconfig
  when:
    bootstrap_enabled
  fetch:
    src: /etc/kubernetes/kubeconfig
    dest: roles/deploy-kubelet/templates/kubeconfig
    flat: yes
