# Copyright 2017 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

release_group: null

images:
  anchor: quay.io/attcomdev/kube-controller-manager:v1.8.0
  controller_manager: quay.io/attcomdev/kube-controller-manager:v1.8.0
  dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  pull_policy: "IfNotPresent"

labels:
  controller_manager:
      node_selector_key: kubernetes-controller-manager
      node_selector_value: enabled

anchor:
  dns_policy: Default
  kubelet:
    manifest_path: /etc/kubernetes/manifests
  period: 15

controller_manager:
  command: /controller-manager
  host_etc_path: /etc/kubernetes/controller-manager
  node_monitor_period: 5s
  node_monitor_grace_period: 20s
  pod_eviction_timeout: 60s

secrets:
  tls:
    ca: placeholder
    cert: placeholder
    key: placeholder
  service_account:
    private_key: placeholder

network:
  kubernetes_netloc: 10.96.0.1
  pod_cidr: 10.97.0.0/16
  service_cidr: 10.96.0.0/16

service:
  name: kubernetes-controller-manager

dependencies:
  controller_manager:

pod:
  mounts:
    controller_manager:
      init_container: null
      controller_manager:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        controller_manager:
          enabled: false
          min_ready_seconds: 0
          max_unavailable: 1
    termination_grace_period:
      controller_manager:
        timeout: 3600
  resources:
    enabled: false
    controller_manager:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"

manifests:
  configmap_bin: true
  configmap_cm: true
  configmap_etc: true
  controller_manager: true
  secret: true
