---
schema: promenade/Genesis/v1
metadata:
  schema: metadata/Document/v1
  name: genesis
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: ${GENESIS_HOSTNAME}
  ip: ${GENESIS_IP}
  labels:
    dynamic:
      - calico-etcd=enabled
      - ceph-mds=enabled
      - ceph-mon=enabled
      - ceph-osd=enabled
      - ceph-rgw=enabled
      - ceph-mgr=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - promenade-genesis=enabled
      - openstack-compute-node=enabled
      - openstack-control-plane=enabled
      - openvswitch=enabled
      - ucp-control-plane=enabled
  images:
    armada: ${IMAGE_ARMADA}
    helm:
      tiller: ${IMAGE_TILLER}
    kubernetes:
      apiserver: ${IMAGE_HYPERKUBE}
      controller-manager: ${IMAGE_HYPERKUBE}
      etcd: ${IMAGE_ETCD}
      scheduler: ${IMAGE_HYPERKUBE}
  files:
    - path: /var/lib/anchor/calico-etcd-bootstrap
      content: ""
      mode: 0644
...
