---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: ${GENESIS_HOSTNAME}
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: ${GENESIS_HOSTNAME}
  ip: ${GENESIS_IP}
  join_ip: ${MASTER1_IP}
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: ${MASTER1_HOSTNAME}
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: ${MASTER1_HOSTNAME}
  ip: ${MASTER1_IP}
  join_ip: ${GENESIS_IP}
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: ${MASTER2_HOSTNAME}
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: ${MASTER2_HOSTNAME}
  ip: ${MASTER2_IP}
  join_ip: ${GENESIS_IP}
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: ${WORKER_HOSTNAME}
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: ${WORKER_HOSTNAME}
  ip: ${WORKER_IP}
  join_ip: ${MASTER1_IP}
  labels:
    dynamic:
      - ucp-control-plane=enabled
...
