---
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6553
    certificate-authority: pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: scheduler
  name: scheduler@kubernetes
current-context: scheduler@kubernetes
kind: Config
preferences: {}
users:
- name: scheduler
  user:
    client-certificate: pki/scheduler.pem
    client-key: pki/scheduler-key.pem
