---
apiVersion: v1
clusters:
- cluster:
    server: https://apiserver.kubernetes.promenade:6443
    certificate-authority: pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: pki/admin.pem
    client-key: pki/admin-key.pem
