{{- if .Values.proxy.enabled }}
---
apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: kube-proxy
  labels:
    component: k8s-proxy
spec:
  template:
    metadata:
      labels:
        tier: node
        component: k8s-proxy
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      dnsPolicy: Default
      nodeSelector:
        {{ .Values.proxy.node_selector.key }}: {{ .Values.proxy.node_selector.value }}
      containers:
      - name: kube-proxy
        image: {{ .Values.images.proxy }}
        command:
        - /proxy
        - --cluster-cidr={{ .Values.network.pod_cidr }}
        - --hostname-override=$(NODE_NAME)
        - --kubeconfig=/etc/kubernetes/proxy/kubeconfig.yaml
        - --proxy-mode=iptables
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
          - name: proxy-cm
            mountPath: /etc/kubernetes/proxy/kubeconfig.yaml
            subPath: kubeconfig.yaml
          - name: proxy-cm
            mountPath: /etc/kubernetes/proxy/pki/proxy.pem
            subPath: proxy.pem
          - name: proxy-cm
            mountPath: /etc/kubernetes/proxy/pki/cluster-ca.pem
            subPath: cluster-ca.pem
          - name: proxy-secret
            mountPath: /etc/kubernetes/proxy/pki/proxy-key.pem
            subPath: proxy-key.pem
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: proxy-cm
          configMap:
            name: kubernetes-proxy
        - name: proxy-secret
          secret:
            secretName: kubernetes-proxy
{{- end }}
