{{- if .Values.controller_manager.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: service-account-private-key
type: Opaque
data:
  service-account.priv: {{ .Values.controller_manager.service_account.private_key | b64enc }}
{{- end }}
