{{- if .Values.scheduler.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-scheduler-cert-keys
type: Opaque
data:
  scheduler-key.pem: {{ .Values.scheduler.tls.key | b64enc }}
{{- end }}
