---
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes:6443
    certificate-authority: /etc/kubernetes/scheduler/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: scheduler
  name: scheduler@kubernetes
current-context: scheduler@kubernetes
kind: Config
preferences: {}
users:
- name: scheduler
  user:
    client-certificate: /etc/kubernetes/scheduler/pki/scheduler.pem
    client-key: /etc/kubernetes/scheduler/pki/scheduler-key.pem
