---
apiVersion: v1
clusters:
- cluster:
    server: http://kubernetes
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user: {}
