---
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6553
    certificate-authority: pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: controller-manager
  name: controller-manager@kubernetes
current-context: controller-manager@kubernetes
kind: Config
preferences: {}
users:
- name: controller-manager
  user:
    client-certificate: pki/controller-manager.pem
    client-key: pki/controller-manager-key.pem
