---
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes:6443
    certificate-authority: /etc/kubernetes/proxy/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: proxy
  name: proxy@kubernetes
current-context: proxy@kubernetes
kind: Config
preferences: {}
users:
- name: proxy
  user:
    client-certificate: /etc/kubernetes/proxy/pki/proxy.pem
    client-key: /etc/kubernetes/proxy/pki/proxy-key.pem
