---
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes
    certificate-authority: /etc/kubernetes/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: controller-manager
  name: controller-manager@kubernetes
current-context: controller-manager@kubernetes
kind: Config
preferences: {}
users:
- name: controller-manager
  user:
    client-certificate: /etc/kubernetes/pki/controller-manager.pem
    client-key: /etc/kubernetes/pki/controller-manager-key.pem
