---
bootstrap:
  apiserver_ips:
    - 192.168.77.10

network:
  cluster_domain: cluster.local
  cluster_dns: 10.96.0.10

node:
  hostname: n1
  ip: 192.168.77.11
  labels:
    - beta.kubernetes.io/arch=amd64
    - node-role.kubernetes.io/master=
