calico:
  ip_autodetection_method: null
  pod_ip_cidr: 10.97.0.0/16
  ctl:
    install_on_host: false

etcd:
  service:
    ip: 10.96.232.136
    port: 6666
  tls:
    ca: |-
      invalid ca
    cert: |-
      invalid cert
    key: |-
      invalid key

images:
  cni: quay.io/calico/cni:v1.10.0
  ctl: quay.io/calico/ctl:v1.5.0
  node: quay.io/calico/node:v2.5.1
  policy_controller: quay.io/calico/kube-policy-controller:v0.7.0
