calico:
  ip_autodetection_method: null
  pod_ip_cidr: 10.97.0.0/16
  mtu: 1500
  ipip: always
  ctl:
    install_on_host: false

etcd:
  service:
    ip: 10.96.232.136
    port: 6666
  tls:
    ca: |-
      invalid ca
    cert: |-
      invalid cert
    key: |-
      invalid key

images:
  cni: quay.io/calico/cni:v1.11.2
  ctl: quay.io/calico/ctl:v1.6.3
  node: quay.io/calico/node:v2.6.5
  policy_controller: quay.io/calico/kube-controllers:v1.0.2

pod:
  resources:
    enabled: false
    calico_node:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    calico_policy_controller:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
