---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-etc
data:
  cluster-ca.pem: {{ .Values.tls.ca | quote }}
  controller-manager.pem: {{ .Values.tls.cert | quote }}
  kubeconfig.yaml: |+
    ---
    apiVersion: v1
    clusters:
    - cluster:
        server: https://{{ .Values.network.kubernetes_netloc }}
        certificate-authority: cluster-ca.pem
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: controller-manager
      name: controller-manager@kubernetes
    current-context: controller-manager@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: controller-manager
      user:
        client-certificate: controller-manager.pem
        client-key: controller-manager-key.pem
