---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}
type: Opaque
data:
  controller-manager-key.pem: {{ .Values.tls.key | b64enc }}
  service-account.priv: {{ .Values.service_account.private_key | b64enc }}
