conf:
  coredns:
    corefile: |
      .:53 {
          errors
          health
          autopath @kubernetes
          kubernetes cluster.local 10.96.0.0/16 10.97.0.0/16 {
            pods disabled
            fallthrough in-addr.arpa ip6.arpa
            upstream 8.8.8.8
            upstream 8.8.4.4
          }
          prometheus :9253
          forward . 8.8.8.8 8.8.4.4
          cache 30
      }

  test:
    names_to_resolve:
      - att.com
      - kubernetes.default.svc.cluster.local

images:
  tags:
    coredns: coredns/coredns:1.1.2
    test: coredns/coredns:1.1.2
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  pull_policy: "IfNotPresent"

labels:
  coredns:
    node_selector_key: coredns
    node_selector_value: enabled

service:
  name: coredns
  ip: 10.96.0.10

pod:
  mounts:
    coredns:
      init_container: null
      coredns:
  resources:
    enabled: false
    coredns:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    pod_test:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"

monitoring:
  prometheus:
    enabled: false
    coredns:
      scrape: true
      port: 9253
