conf:
  coredns:
    corefile: |
      .:53 {
          errors
          health
          autopath @kubernetes
          kubernetes cluster.local 10.96.0.0/16 10.97.0.0/16 {
            pods disabled
            fallthrough in-addr.arpa ip6.arpa
            upstream 8.8.8.8
            upstream 8.8.4.4
          }
          prometheus :9253
          proxy . 8.8.8.8
          proxy . 8.8.4.4
          cache 30
      }

  test:
    names_to_resolve:
      - att.com
      - kubernetes.default.svc.cluster.local

pod:
  mounts:
    coredns:
      init_container: null
      core_dns:
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    termination_grace_period:
      coredns:
        timeout: 3600
  resources:
    enabled: false
    core_dns:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"

images:
  tags:
    coredns: coredns/coredns:1.0.5
    test: coredns/coredns:1.0.5
  pull_policy: "IfNotPresent"

node_selector: {}

service:
  name: coredns
  ip: 10.96.0.10
