conf:
  coredns:
    corefile: |
      .:53 {
          errors
          health
          autopath @kubernetes
          kubernetes cluster.local 10.96.0.0/16 10.97.0.0/16 {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            upstream 8.8.8.8
            upstream 8.8.4.4
          }
          prometheus :9153
          proxy . 8.8.8.8
          proxy . 8.8.4.4
          cache 30
      }

images:
  tags:
    coredns: coredns/coredns:1.0.5
  pull_policy: "IfNotPresent"

node_selector: {}

service:
  name: coredns
  ip: 10.96.0.10
