---
apiVersion: v1
kind: Pod
metadata:
  name: tiller-deploy
  namespace: kube-system
  labels:
    app: promenade
    component: genesis-tiller
spec:
  dnsPolicy: Default
  hostNetwork: true
  containers:
  - env:
    - name: TILLER_NAMESPACE
      value: kube-system
    image: {{ config['Genesis:images.helm.tiller'] }}
    command:
      - /tiller
      - -logtostderr
      - -v
      - "99"
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /liveness
        port: 44135
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: tiller
    ports:
    - containerPort: 44134
      name: tiller
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readiness
        port: 44135
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
