---
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1
    certificate-authority: /target/etc/kubernetes/genesis/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: genesis
  name: genesis@kubernetes
current-context: genesis@kubernetes
kind: Config
preferences: {}
users:
- name: genesis
  user:
    client-certificate: /target/etc/kubernetes/genesis/pki/genesis.pem
    client-key: /target/etc/kubernetes/genesis/pki/genesis-key.pem
