anchor:
  dns_policy: Default
  etcdctl_endpoint: example-etcd
  host_data_path: /var/lib/etcd/example

  kubelet:
    manifest_path: /etc/kubernetes/manifests

  node_selector:
    key: etcd-example
    value: enabled

  termination_grace_period: 3600
  period: 15

  tls:
    cert: placeholder
    key: placeholder

etcd:
  host_etc_path: /etc/etcd-example
  host_data_path: /var/lib/etcd/example
  cleanup_data: true

service:
  name: example-etcd
  ip: null
  client:
    port: 2379
    target_port: 2379
  peer:
    port: 2380
    target_port: 2380

bootstrapping:
  enabled: false
  host_directory: /var/lib/anchor/etcd-example
  filename: bootstrap
  # XXX Can I just generalize to an anchor timeout?
  timeout: 300

tls:
  client:
    ca: placeholder
  peer:
    ca: placeholder

nodes:
  - name: example-0
    tls:
      client:
        cert: placeholder
        key: placeholder
      peer:
        cert: placeholder
        key: placeholder

images:
  etcd: quay.io/coreos/etcd:v3.2.7
  etcdctl: quay.io/coreos/etcd:v3.2.7
