---
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes:6443
    certificate-authority: /etc/kubernetes/asset-loader/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: asset-loader
  name: asset-loader@kubernetes
current-context: asset-loader@kubernetes
kind: Config
preferences: {}
users:
- name: asset-loader
  user:
    client-certificate: /etc/kubernetes/asset-loader/pki/asset-loader.pem
    client-key: /etc/kubernetes/asset-loader/pki/asset-loader-key.pem
