---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n0
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n0
  ip: 192.168.77.10
  join_ip: 192.168.77.11
  labels:
    dynamic:
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n1
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n1
  ip: 192.168.77.11
  join_ip: 192.168.77.10
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n2
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n2
  ip: 192.168.77.12
  join_ip: 192.168.77.10
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n3
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n3
  ip: 192.168.77.13
  join_ip: 192.168.77.11
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
...
