---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker.io"
    - "vim"
    - "ethtool"
    - "traceroute"
    - "git"
    - "build-essential"
    - "lldpd"

- name: Insert Temporary Hosts File Entry for FQDN Resolution
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }} {{ api_server_fqdn }}"
    state: present

# Obtains auth/kubeconfig from loaded bootkube assets
- name: Install kubeconfig from pre-generated assets
  when:
    - (bootstrap_enabled == 'true') and (bootkube_render == 'false')
  copy:
    src: '../files/bootkube/assets/auth/kubeconfig'
    dest: '/etc/kubernetes/kubeconfig'
    owner: root
    group: root
    mode: 0644

# Obtains auth/kubeconfig from created bootkube assets
- name: Install kubeconfig from promenade-generated assets
  when:
    - (bootstrap_enabled == 'true') and (bootkube_render == 'true')
  copy:
    src: '../files/backup/bootkube/assets/auth/kubeconfig'
    dest: '/etc/kubernetes/kubeconfig'
    owner: root
    group: root
    mode: 0644
