---
apiVersion: v1
kind: Pod
metadata:
  name: coredns
  namespace: kube-system
  labels:
    # NOTE(mark-burnett): This is a host initialization Pod and should not be
    # included in the Kubernetes DNS service, so ensure it does not get
    # selected.
    coredns-service: disabled
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
    - name: coredns
      image: {{ config['HostSystem:images.coredns'] }}
      command:
        - /coredns
        - -conf
        - /etc/coredns/Corefile
      volumeMounts:
        - name: config
          mountPath: /etc/coredns
          readOnly: true
        - name: tls
          mountPath: /etc/coredns-pki
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: /etc/coredns
    - name: tls
      hostPath:
        path: /etc/kubernetes/admin/pki
