---
apiVersion: v1
kind: Pod
metadata:
  name: coredns
  namespace: kube-system
  labels:
    coredns-service: enabled
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
    - name: coredns
      image: {{ config['HostSystem:images.coredns'] }}
      command:
        - /coredns
        - -conf
        - /etc/coredns/Corefile
      volumeMounts:
        - name: config
          mountPath: /etc/coredns
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: /etc/coredns
